name: stream_video_screen_sharing
description: >
  Official Screen Sharing Plugin for Stream Video Flutter that enables sharing device screens
  during video calls.
version: 0.8.4
homepage: https://getstream.io/video/
repository: https://github.com/GetStream/stream-video-flutter
issue_tracker: https://github.com/GetStream/stream-video-flutter/issues

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dependency_overrides:
  dart_webrtc:
    git:
      url: https://github.com/StiftTechnologies/dart-webrtc.git
      ref: 8431d6c54339333f2681c0caaeb875d8c863826c

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: StreamVideoScreenSharingPlugin
